on:
  push:
  pull_request:

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install node v20
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: yarn install
      run: yarn install
    - name: Build
      run: yarn build